# Generated by Django 5.1.6 on 2025-03-30 14:48

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job')},
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'recruiter')},
            },
        ),
        migrations.DeleteModel(
            name='FollowCompany',
        ),
    ]
