# Generated by Django 5.1.6 on 2025-03-20 15:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatars',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Specialized',
            field=models.CharField(default='Chưa phân loại', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
