# Generated by Django 5.1.6 on 2025-03-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_options_remove_company_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Specialized',
            new_name='specialized',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
